//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalServicesAutorLibro
{
    using System;
    using System.Collections.Generic;
    
    public partial class autores
    {
        public autores()
        {
            this.libros = new HashSet<libros>();
        }
    
        public int id_autores { get; set; }
        public string autor_uno_nombre { get; set; }
        public string autor_dos_nombre { get; set; }
        public string autor_tres_nombre { get; set; }
    
        public virtual ICollection<libros> libros { get; set; }
    }
}
