//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalServicesAutorLibro
{
    using System;
    using System.Collections.Generic;
    
    public partial class libros
    {
        public int id_libro { get; set; }
        public string titulo { get; set; }
        public int id_autores { get; set; }
        public string editorial { get; set; }
        public string fecha_publicacion { get; set; }
        public string idioma { get; set; }
        public int numero_paginas { get; set; }
    
        public virtual autores autores { get; set; }
    }
}
