//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalServicesAutorLibro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CapaEntityFramework : DbContext
    {
        public CapaEntityFramework()
            : base("name=CapaEntityFramework")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<autores> autores { get; set; }
        public DbSet<libros> libros { get; set; }
    
        public virtual int create_autor(string autor_uno_nombre, string autor_dos_nombre, string autor_tres_nombre)
        {
            var autor_uno_nombreParameter = autor_uno_nombre != null ?
                new ObjectParameter("autor_uno_nombre", autor_uno_nombre) :
                new ObjectParameter("autor_uno_nombre", typeof(string));
    
            var autor_dos_nombreParameter = autor_dos_nombre != null ?
                new ObjectParameter("autor_dos_nombre", autor_dos_nombre) :
                new ObjectParameter("autor_dos_nombre", typeof(string));
    
            var autor_tres_nombreParameter = autor_tres_nombre != null ?
                new ObjectParameter("autor_tres_nombre", autor_tres_nombre) :
                new ObjectParameter("autor_tres_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("create_autor", autor_uno_nombreParameter, autor_dos_nombreParameter, autor_tres_nombreParameter);
        }
    
        public virtual int create_libro(string titulo, Nullable<int> id_autores, string editorial, string fecha_publicacion, string idioma, Nullable<int> numero_paginas)
        {
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var id_autoresParameter = id_autores.HasValue ?
                new ObjectParameter("id_autores", id_autores) :
                new ObjectParameter("id_autores", typeof(int));
    
            var editorialParameter = editorial != null ?
                new ObjectParameter("editorial", editorial) :
                new ObjectParameter("editorial", typeof(string));
    
            var fecha_publicacionParameter = fecha_publicacion != null ?
                new ObjectParameter("fecha_publicacion", fecha_publicacion) :
                new ObjectParameter("fecha_publicacion", typeof(string));
    
            var idiomaParameter = idioma != null ?
                new ObjectParameter("idioma", idioma) :
                new ObjectParameter("idioma", typeof(string));
    
            var numero_paginasParameter = numero_paginas.HasValue ?
                new ObjectParameter("numero_paginas", numero_paginas) :
                new ObjectParameter("numero_paginas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("create_libro", tituloParameter, id_autoresParameter, editorialParameter, fecha_publicacionParameter, idiomaParameter, numero_paginasParameter);
        }
    
        public virtual int delete_autor(Nullable<int> id_autores)
        {
            var id_autoresParameter = id_autores.HasValue ?
                new ObjectParameter("id_autores", id_autores) :
                new ObjectParameter("id_autores", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_autor", id_autoresParameter);
        }
    
        public virtual int delete_libro(Nullable<int> id_libro)
        {
            var id_libroParameter = id_libro.HasValue ?
                new ObjectParameter("id_libro", id_libro) :
                new ObjectParameter("id_libro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_libro", id_libroParameter);
        }
    
        public virtual ObjectResult<select_autor_Result> select_autor(Nullable<int> id_autor)
        {
            var id_autorParameter = id_autor.HasValue ?
                new ObjectParameter("id_autor", id_autor) :
                new ObjectParameter("id_autor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_autor_Result>("select_autor", id_autorParameter);
        }
    
        public virtual ObjectResult<select_autores_Result> select_autores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_autores_Result>("select_autores");
        }
    
        public virtual ObjectResult<select_libro_Result> select_libro(Nullable<int> id_libro)
        {
            var id_libroParameter = id_libro.HasValue ?
                new ObjectParameter("id_libro", id_libro) :
                new ObjectParameter("id_libro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_libro_Result>("select_libro", id_libroParameter);
        }
    
        public virtual ObjectResult<select_libros_Result> select_libros()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_libros_Result>("select_libros");
        }
    
        public virtual int update_autores(Nullable<int> id_autores, string autor_uno_nombre, string autor_dos_nombre, string autor_tres_nombre)
        {
            var id_autoresParameter = id_autores.HasValue ?
                new ObjectParameter("id_autores", id_autores) :
                new ObjectParameter("id_autores", typeof(int));
    
            var autor_uno_nombreParameter = autor_uno_nombre != null ?
                new ObjectParameter("autor_uno_nombre", autor_uno_nombre) :
                new ObjectParameter("autor_uno_nombre", typeof(string));
    
            var autor_dos_nombreParameter = autor_dos_nombre != null ?
                new ObjectParameter("autor_dos_nombre", autor_dos_nombre) :
                new ObjectParameter("autor_dos_nombre", typeof(string));
    
            var autor_tres_nombreParameter = autor_tres_nombre != null ?
                new ObjectParameter("autor_tres_nombre", autor_tres_nombre) :
                new ObjectParameter("autor_tres_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_autores", id_autoresParameter, autor_uno_nombreParameter, autor_dos_nombreParameter, autor_tres_nombreParameter);
        }
    
        public virtual int update_libro(Nullable<int> id_libro, string titulo, Nullable<int> id_autores, string editorial, string fecha_publicacion, string idioma, Nullable<int> numero_paginas)
        {
            var id_libroParameter = id_libro.HasValue ?
                new ObjectParameter("id_libro", id_libro) :
                new ObjectParameter("id_libro", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var id_autoresParameter = id_autores.HasValue ?
                new ObjectParameter("id_autores", id_autores) :
                new ObjectParameter("id_autores", typeof(int));
    
            var editorialParameter = editorial != null ?
                new ObjectParameter("editorial", editorial) :
                new ObjectParameter("editorial", typeof(string));
    
            var fecha_publicacionParameter = fecha_publicacion != null ?
                new ObjectParameter("fecha_publicacion", fecha_publicacion) :
                new ObjectParameter("fecha_publicacion", typeof(string));
    
            var idiomaParameter = idioma != null ?
                new ObjectParameter("idioma", idioma) :
                new ObjectParameter("idioma", typeof(string));
    
            var numero_paginasParameter = numero_paginas.HasValue ?
                new ObjectParameter("numero_paginas", numero_paginas) :
                new ObjectParameter("numero_paginas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_libro", id_libroParameter, tituloParameter, id_autoresParameter, editorialParameter, fecha_publicacionParameter, idiomaParameter, numero_paginasParameter);
        }
    }
}
